version: "1"
module_version: 0.0.2

test_defaults:
  before_init: ["terraform fmt -check"]

# AC: Using terraform_versions doesn't work properly with a monorepo, so specify test cases instead:
tests:
- name: simple-example
  project_root: examples/simple-example
